// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Web_Api__multitracks.Models;

namespace Web_Api__multitracks.Data
{
    public partial class MultiTracksDBContext
    {
        private IMultiTracksDBContextProcedures _procedures;

        public virtual IMultiTracksDBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new MultiTracksDBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IMultiTracksDBContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetArtistDetailsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<GetAssessmentStepsResult>().HasNoKey().ToView(null);
        }
    }

    public partial class MultiTracksDBContextProcedures : IMultiTracksDBContextProcedures
    {
        private readonly MultiTracksDBContext _context;

        public MultiTracksDBContextProcedures(MultiTracksDBContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetArtistDetailsResult>> GetArtistDetailsAsync(int? artistID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = returnValue?._value,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "artistID",
                    Value = artistID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetArtistDetailsResult>("EXEC @returnValue = [dbo].[GetArtistDetails] @artistID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<GetAssessmentStepsResult>> GetAssessmentStepsAsync(int? stepID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = returnValue?._value,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "stepID",
                    Value = stepID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetAssessmentStepsResult>("EXEC @returnValue = [dbo].[GetAssessmentSteps] @stepID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
