// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_Api__multitracks.Models
{
    public partial class AssessmentSteps
    {
        public int stepID { get; set; }
        public string text { get; set; }
    }
}