// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Web_Api__multitracks.Models
{
    public partial class GetArtistDetailsResult
    {
        public string title { get; set; }
    }
}
